services:
  - type: web
    name: carnes-del-rancho-web
    env: python
    region: oregon  # o la regi√≥n de Render que prefieras, p.ej. "oregon" o "vienna"
    plan: free  # si quieres empezar gratis
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn carnes_del_rancho.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
      - key: ALLOWED_HOSTS
        value: "www.tudominio.com, carnes-del-rancho.onrender.com"
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
    staticPublishPath: staticfiles
